### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by notmyst33d** [RedmiNote10S/android_device_redmi_rosemary#1]
A list of whats broken and needs fixing
- [x] RIL on secret/maltose
- [x] Bluetooth audio
- [x] Mtkperf Scroll Boost (Abandoned works)
- [x] DT2W
- [x] VoLTE
- [x] Offline Charging
- [x] In-call volume input/output
- [x] SELinux
